spring:
  application:
    name: livin
    
  datasource:
    url: jdbc:mysql://${RDS_IP}:3306/efublivin?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
	        format_sql: true
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
      
kakao:
  api:
    key: ${KAKAO_MAP_API_KEY}
    
naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    
logging:
  level:
    root: INFO
